### PR TITLE
updated packages

### PR DESCRIPTION
**Pull request by maikelmclauflin**
updated packages to not have security vulnerabilities.

### CODE REVIEW

**Comment by evanshortiss** [comment]
@maikelmclauflin could you remove Node 4 & 5 from the CI config (these are failing) and add 8 and 10? Something [like this](https://github.com/evanshortiss/exposure-utility/blob/master/.travis.yml#L3) should work.

Could you also use  `~` instead of `^` in the package.json? Happy to merge once that's done.

Thanks for the PR

**Comment by evanshortiss** [comment]
Oh, and the engines field needs to be updated in [package.json](https://github.com/evanshortiss/express-joi-validation/blob/master/package.json#L56) too for Node.js v6

**Comment by maikelmclauflin** [comment]
fixes #10

**Comment by evanshortiss** [comment]
@maikelmclauflin one more thing, and sorry about this, could remove the package lock json? Looks good to merge after that

**Comment by maikelmclauflin** [comment]
@evanshortiss are you sure? 
https://docs.npmjs.com/files/package-lock.json
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by evanshortiss** [comment]
@maikelmclauflin yeah, I only check those into user facing applications, but not modules. Seems to be a common pattern in OSS projects, e.g express, fastify, lodash, and others don't check it in.

Edit: My reasoning is highlighted by the comments on the top answer in the StackOverflow link you included.

**Comment by maikelmclauflin** [comment]
Fair enough. Removed

**Comment by evanshortiss** [comment]
@maikelmclauflin merged can cut a release after your other PR is merged. Just had one comment on it.

**Pull request merged**
